

FROM python:3.9-slim

RUN python3 -m venv test-env

RUN pip install poetry
COPY poetry.lock pyproject.toml .

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

WORKDIR /users
COPY ./ ./

CMD python3 -m pytest ./tests
